name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

#concurrency:
#  group: "pages"
#  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET (global.json)
        uses: actions/setup-dotnet@v4

      - name: Build  
        run: dotnet build Portfolio/Portfolio.csproj -c Release

      - name: Publish
        run: dotnet publish Portfolio/Portfolio.csproj -c Release -o release

      - name: Debug CSS generation
        run: |
          echo "----- Source generated razor.css files -----"
          find Portfolio/ -name "*.razor.css" | sort
          
          echo ""
          echo "----- Scoped compiled rz.scp.css files in obj/ -----"
          find Portfolio/ -name "*.rz.scp.css" | sort
          
          echo ""
          echo "----- Published bundle -----"
          find release/wwwroot -name "*.css" | sort
          
          echo ""
          echo "----- STYLES.CSS HEAD -----"
          head -n 50 release/wwwroot/css/styles.css || true
          echo "----- STYLES.CSS TAIL -----"
          tail -n 50 release/wwwroot/css/styles.css || true

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
